// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Comment = 2,
  LabelDef = 3,
  DotWord = 4,
  Directive = 5,
  Identifier = 7,
  Register = 8,
  Number = 9,
  StringLiteral = 10,
  CharLiteral = 11,
  PcRef = 12,
  MnemonicIO = 13,
  MnemonicBranch = 14,
  MnemonicCore = 15,
  MnemonicPlus = 16
