#!/usr/bin/env node
/**
 * errors-export.js — export ~/.lccjs/velocity.db errors table → stats/errors.csv.
 *
 * Writes an auto-generated comment header then all error rows ordered by id.
 * Atomic write (temp file → rename) — a crash mid-write never leaves a partial CSV.
 * Runnable directly or via npm run errors:export.
 *
 * Usage:
 *   node scripts/errors-export.js
 *   npm run errors:export
 *   npm run errors:export -- --force   # bypass main-checkout guard
 */
'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const Database = require('better-sqlite3');

const DB_PATH = process.env.VELOCITY_DB   || path.join(os.homedir(), '.lccjs', 'velocity.db');
const CSV     = process.env.ERRORS_CSV    || path.join(__dirname, '..', 'stats', 'errors.csv');
const TMP     = CSV + '.tmp';

const COLS = [
  'id', 'occurred_iso', 'agent', 'model',
  'ticket', 'repo', 'error_type', 'message', 'context', 'notes',
];

function encodeField(val) {
  if (val == null) return '';
  const s = String(val);
  if (s.includes(',') || s.includes('"') || s.includes('\n') || s.includes('\r')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

function encodeRow(obj) {
  return COLS.map(c => encodeField(obj[c])).join(',');
}

// Returns true when the script is running from the main checkout (not a worktree).
// In a worktree, .git is a file containing "gitdir: ..."; in the main checkout it is a directory.
function isMainCheckout() {
  const dotGit = path.join(__dirname, '..', '.git');
  try {
    return fs.statSync(dotGit).isDirectory();
  } catch (_) {
    return false;
  }
}

function exportCSV({ force = false } = {}) {
  if (!force && isMainCheckout()) {
    console.log('Skipping CSV export — running from main checkout. Pass --force to override.');
    return;
  }

  if (!fs.existsSync(DB_PATH)) {
    console.error(`DB not found at ${DB_PATH} — run npm run error:seed first`);
    process.exit(1);
  }

  const db = new Database(DB_PATH, { readonly: true });

  // Guard: errors table may not exist yet (pre-seed)
  const tableExists = db.prepare(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='errors'"
  ).get();
  if (!tableExists) {
    db.close();
    console.error('errors table not found in DB — run npm run error:seed first');
    process.exit(1);
  }

  const rows = db.prepare('SELECT * FROM errors ORDER BY id').all();
  db.close();

  const lines = [
    '# AUTO-GENERATED by scripts/errors-export.js — do not edit directly. Source: ~/.lccjs/velocity.db',
    COLS.join(','),
    ...rows.map(encodeRow),
  ];

  fs.writeFileSync(TMP, lines.join('\n') + '\n');
  fs.renameSync(TMP, CSV);
  console.log(`Exported ${rows.length} rows → ${CSV}`);
}

module.exports = { exportCSV, isMainCheckout };

if (require.main === module) {
  exportCSV({ force: process.argv.includes('--force') });
}
