#!/usr/bin/env node
/**
 * rice-export.js — export ~/.lccjs/lccjs.db rice table → stats/rice-scores.csv.
 *
 * Writes an auto-generated comment header then all rice rows ordered by rice_rank.
 * Atomic write (temp file → rename) — a crash mid-write never leaves a partial CSV.
 * Runnable directly or via npm run rice:export.
 *
 * Usage:
 *   node scripts/rice-export.js
 *   npm run rice:export
 *   npm run rice:export -- --force   # bypass main-checkout guard
 */
'use strict';

const fs   = require('fs');
const path = require('path');
const Database = require('better-sqlite3');
const { DB_PATH } = require('./db-path');

const CSV = process.env.RICE_CSV || path.join(__dirname, '..', 'stats', 'rice-scores.csv');
const TMP = CSV + '.tmp';

const COLS = [
  'id', 'issue', 'title', 'type',
  'r', 'i', 'c_pct', 'e_hrs', 'rice_score', 'rice_rank', 'yegor_priority',
  'actionable', 'labels', 'notes',
  'scored_iso', 'scored_by', 'repo',
];

function encodeField(val) {
  if (val == null) return '';
  const s = String(val);
  if (s.includes(',') || s.includes('"') || s.includes('\n') || s.includes('\r')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

function encodeRow(obj) {
  return COLS.map(c => encodeField(obj[c])).join(',');
}

function isMainCheckout() {
  const dotGit = path.join(__dirname, '..', '.git');
  try { return fs.statSync(dotGit).isDirectory(); } catch (_) { return false; }
}

function exportCSV({ force = false } = {}) {
  if (!force && isMainCheckout()) {
    console.log('Skipping CSV export — running from main checkout. Pass --force to override.');
    return;
  }

  if (!fs.existsSync(DB_PATH)) {
    console.error(`DB not found at ${DB_PATH} — run npm run rice:seed first`);
    process.exit(1);
  }

  const db = new Database(DB_PATH, { readonly: true });

  const tableExists = db.prepare(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='rice'"
  ).get();
  if (!tableExists) {
    db.close();
    console.error('rice table not found in DB — run npm run rice:seed first');
    process.exit(1);
  }

  const rows = db.prepare('SELECT * FROM rice ORDER BY rice_rank, id').all();
  db.close();

  const lines = [
    '# AUTO-GENERATED by scripts/rice-export.js — do not edit directly. Source: ~/.lccjs/lccjs.db',
    COLS.join(','),
    ...rows.map(encodeRow),
  ];

  fs.writeFileSync(TMP, lines.join('\n') + '\n');
  fs.renameSync(TMP, CSV);
  console.log(`Exported ${rows.length} rows → ${CSV}`);
}

module.exports = { exportCSV, isMainCheckout };

if (require.main === module) {
  exportCSV({ force: process.argv.includes('--force') });
}
