#!/usr/bin/env node
/**
 * velocity-export.js — export ~/.lccjs/velocity.db → docs/puzzle-velocity.csv.
 *
 * Writes an auto-generated comment header then all velocity rows ordered by id.
 * Atomic write (temp file → rename) — a crash mid-write never leaves a partial CSV.
 * Called automatically by velocity-log.js after every INSERT; also runnable directly.
 *
 * Usage:
 *   node scripts/velocity-export.js
 *   npm run velocity:export
 */
'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const Database = require('better-sqlite3');

const DB_PATH = path.join(os.homedir(), '.lccjs', 'velocity.db');
const CSV     = path.join(__dirname, '..', 'docs', 'puzzle-velocity.csv');
const TMP     = CSV + '.tmp';

const COLS = [
  'id', 'ticket', 'title', 'role',
  'h_min', 'c_min', 'actual_min', 'delta_h_min', 'delta_c_min',
  'started_iso', 'finished_iso', 'closed_commit',
  'notes', 'agent', 'model',
];

function encodeField(val) {
  if (val == null) return '';
  const s = String(val);
  if (s.includes(',') || s.includes('"') || s.includes('\n') || s.includes('\r')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

function encodeRow(obj) {
  return COLS.map(c => encodeField(obj[c])).join(',');
}

// @todo #320:30m/DEV skip export when running from main checkout (not a worktree) — guard goes here in exportCSV(); detect via fs.statSync(path.join(__dirname,'..', '.git')).isDirectory(); see docs/research/csv-from-main-footgun.md
function exportCSV() {
  if (!fs.existsSync(DB_PATH)) {
    console.error(`DB not found at ${DB_PATH} — run npm run velocity:seed first`);
    process.exit(1);
  }

  const db = new Database(DB_PATH, { readonly: true });
  const rows = db.prepare('SELECT * FROM velocity ORDER BY id').all();
  db.close();

  const lines = [
    '# AUTO-GENERATED by scripts/velocity-export.js — do not edit directly. Source: ~/.lccjs/velocity.db',
    COLS.join(','),
    ...rows.map(encodeRow),
  ];

  fs.writeFileSync(TMP, lines.join('\n') + '\n');
  fs.renameSync(TMP, CSV);
  console.log(`Exported ${rows.length} rows → ${CSV}`);
}

module.exports = { exportCSV };

if (require.main === module) {
  exportCSV();
}
