const fs = require('fs');
const path = require('path');

// Minimal RFC 4180 CSV line parser (handles quote-doubling, quoted commas).
function parseCSVLine(line) {
  const fields = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') { field += '"'; i++; }
      else if (ch === '"') { inQuotes = false; }
      else { field += ch; }
    } else {
      if (ch === '"') { inQuotes = true; }
      else if (ch === ',') { fields.push(field); field = ''; }
      else { field += ch; }
    }
  }
  fields.push(field);
  return fields;
}

// Integrity guards for docs/puzzle-velocity.csv, the read-only export of
// ~/.lccjs/lccjs.db (regenerated by `npm run velocity:export`). These
// invariants catch export bugs: CRLF injection and duplicate rows.
describe('docs/puzzle-velocity.csv integrity', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  test('is LF-only — no carriage returns', () => {
    const crLines = raw
      .split('\n')
      .map((line, i) => [i + 1, line])
      .filter(([, line]) => line.includes('\r'))
      .map(([n]) => n);
    expect(crLines).toEqual([]);
  });

  test('has no byte-identical duplicate rows', () => {
    const seen = new Map();
    const dups = [];
    raw.split('\n').forEach((line, i) => {
      if (line === '') return; // ignore blank / trailing lines
      if (seen.has(line)) dups.push({ firstLine: seen.get(line) + 1, dupLine: i + 1, head: line.slice(0, 24) });
      else seen.set(line, i);
    });
    expect(dups).toEqual([]);
  });
});

// Concern #314-3: model column must be documented in docs/puzzle-velocity.md.
describe('docs/puzzle-velocity.md — column reference', () => {
  const mdPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.md');
  const md = fs.readFileSync(mdPath, 'utf8');

  test('documents the `model` column in the column table', () => {
    // The column table uses markdown rows like: | `model` | ...
    expect(md).toMatch(/\|\s*`model`\s*\|/);
  });
});

// Concern #314-2: every row logged on or after the model column was introduced
// (#275, DB row 126) should have a non-empty model value.  Rows before that
// are legitimately blank (pre-column era); we track the cutoff by id.
// Rows with agent='TEST' are excluded: they are test-suite artifacts injected
// by velocity-log tests into the shared DB (#940 tracks the isolation fix).
describe('docs/puzzle-velocity.csv — model column backfill', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  const lines = raw.split('\n').filter(l => l && !l.startsWith('#'));
  const header = parseCSVLine(lines[0]);
  const idIdx    = header.indexOf('id');
  const modelIdx = header.indexOf('model');
  const agentIdx = header.indexOf('agent');
  const dataRows = lines.slice(1).filter(Boolean);

  // id 126 = first row that introduced the model column (ticket #275, DRAGONFRUIT).
  const MODEL_COLUMN_SINCE_ID = 126;

  test('all non-TEST rows with id >= 126 have a non-empty model value', () => {
    const missing = dataRows
      .map(line => parseCSVLine(line))
      .filter(fields => Number(fields[idIdx]) >= MODEL_COLUMN_SINCE_ID)
      .filter(fields => fields[agentIdx] !== 'TEST')
      .filter(fields => !fields[modelIdx])
      .map(fields => ({ id: fields[idIdx], ticket: fields[1] }));
    expect(missing).toEqual([]);
  });
});

// Concern #314-5, relaxed by #1184 (notice-not-prevent) and extended by #1193:
// the canonical short form for a model is <family>-<major.minor> (e.g. sonnet-4.6,
// opus-4.8) or <family>-<label> for experimental/non-Claude models (e.g. owl-alpha).
// Lowercase family. A value that doesn't match the updated regex is reported
// (notice-not-prevent) but never fails the build — models are an open-growth list.
// The report surfaces drift for later human normalisation. The validator in
// velocity-log.js also only warns.
describe('docs/puzzle-velocity.csv — model column naming convention', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  // Parse data rows (skip comment line + header).
  const lines = raw.split('\n').filter(l => l && !l.startsWith('#'));
  const header = parseCSVLine(lines[0]);
  const modelIdx = header.indexOf('model');
  const dataRows = lines.slice(1).filter(Boolean);

  test('CSV export contains a `model` column', () => {
    expect(modelIdx).toBeGreaterThanOrEqual(0);
  });

  // Report-only: surface non-canonical model values without failing the build.
  test('reports any non-canonical model values (notice-not-prevent, #1184 + #1193 extension)', () => {
    const canonical = /^[a-z]+-[a-z0-9.]+$/;
    const nonCanonical = dataRows
      .map(line => parseCSVLine(line))
      .map((fields, i) => ({ row: i + 2, value: fields[modelIdx] }))
      .filter(({ value }) => value && !canonical.test(value));
    if (nonCanonical.length > 0) {
      // eslint-disable-next-line no-console
      console.warn(
        `[velocity-csv] note: ${nonCanonical.length} non-canonical model value(s) present ` +
        `(new releases or drift to normalise — not a failure):\n` +
        nonCanonical.map(v => `  row ${v.row}: "${v.value}"`).join('\n'));
    }
    // The contract is observability, not enforcement: collection must succeed,
    // but a non-canonical value never reds the build.
    expect(Array.isArray(nonCanonical)).toBe(true);
  });
});
