const fs = require('fs');
const path = require('path');

// Minimal RFC 4180 CSV line parser (handles quote-doubling, quoted commas).
function parseCSVLine(line) {
  const fields = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') { field += '"'; i++; }
      else if (ch === '"') { inQuotes = false; }
      else { field += ch; }
    } else {
      if (ch === '"') { inQuotes = true; }
      else if (ch === ',') { fields.push(field); field = ''; }
      else { field += ch; }
    }
  }
  fields.push(field);
  return fields;
}

// Integrity guards for docs/puzzle-velocity.csv, the read-only export of
// ~/.lccjs/lccjs.db (regenerated by `npm run velocity:export`). These
// invariants catch export bugs: CRLF injection and duplicate rows.
describe('docs/puzzle-velocity.csv integrity', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  test('is LF-only — no carriage returns', () => {
    const crLines = raw
      .split('\n')
      .map((line, i) => [i + 1, line])
      .filter(([, line]) => line.includes('\r'))
      .map(([n]) => n);
    expect(crLines).toEqual([]);
  });

  test('has no byte-identical duplicate rows', () => {
    const seen = new Map();
    const dups = [];
    raw.split('\n').forEach((line, i) => {
      if (line === '') return; // ignore blank / trailing lines
      if (seen.has(line)) dups.push({ firstLine: seen.get(line) + 1, dupLine: i + 1, head: line.slice(0, 24) });
      else seen.set(line, i);
    });
    expect(dups).toEqual([]);
  });
});

// Concern #314-3: model column must be documented in docs/puzzle-velocity.md.
describe('docs/puzzle-velocity.md — column reference', () => {
  const mdPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.md');
  const md = fs.readFileSync(mdPath, 'utf8');

  test('documents the `model` column in the column table', () => {
    // The column table uses markdown rows like: | `model` | ...
    expect(md).toMatch(/\|\s*`model`\s*\|/);
  });
});

// Concern #314-2: every row logged on or after the model column was introduced
// (#275, DB row 126) should have a non-empty model value.  Rows before that
// are legitimately blank (pre-column era); we track the cutoff by id.
describe('docs/puzzle-velocity.csv — model column backfill', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  const lines = raw.split('\n').filter(l => l && !l.startsWith('#'));
  const header = parseCSVLine(lines[0]);
  const idIdx    = header.indexOf('id');
  const modelIdx = header.indexOf('model');
  const dataRows = lines.slice(1).filter(Boolean);

  // id 126 = first row that introduced the model column (ticket #275, DRAGONFRUIT).
  const MODEL_COLUMN_SINCE_ID = 126;

  test('all rows with id >= 126 have a non-empty model value', () => {
    const missing = dataRows
      .map(line => parseCSVLine(line))
      .filter(fields => Number(fields[idIdx]) >= MODEL_COLUMN_SINCE_ID)
      .filter(fields => !fields[modelIdx])
      .map(fields => ({ id: fields[idIdx], ticket: fields[1] }));
    expect(missing).toEqual([]);
  });
});

// Concern #314-5: all non-empty model values in the CSV must follow the
// canonical short form: <family>-<major>.<minor>  e.g. sonnet-4.6, opus-4.8
// Convention chosen: lowercase family name, version with a dot (not dashes).
describe('docs/puzzle-velocity.csv — model column naming convention', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  // Parse data rows (skip comment line + header).
  const lines = raw.split('\n').filter(l => l && !l.startsWith('#'));
  const header = parseCSVLine(lines[0]);
  const modelIdx = header.indexOf('model');
  const dataRows = lines.slice(1).filter(Boolean);

  test('CSV export contains a `model` column', () => {
    expect(modelIdx).toBeGreaterThanOrEqual(0);
  });

  test('all non-empty model values match canonical format: <family>-<major>.<minor>', () => {
    const canonical = /^[a-z]+-\d+\.\d+$/;
    const violations = dataRows
      .map(line => parseCSVLine(line))
      .map((fields, i) => ({ row: i + 2, value: fields[modelIdx] }))
      .filter(({ value }) => value && !canonical.test(value));
    expect(violations).toEqual([]);
  });
});
