const fs = require('fs');
const path = require('path');

// Integrity guards for docs/puzzle-velocity.csv, the read-only export of
// ~/.lccjs/velocity.db (regenerated by `npm run velocity:export`). These
// invariants catch export bugs: CRLF injection and duplicate rows.
describe('docs/puzzle-velocity.csv integrity', () => {
  const csvPath = path.join(__dirname, '..', '..', 'docs', 'puzzle-velocity.csv');
  const raw = fs.readFileSync(csvPath, 'utf8');

  test('is LF-only — no carriage returns', () => {
    const crLines = raw
      .split('\n')
      .map((line, i) => [i + 1, line])
      .filter(([, line]) => line.includes('\r'))
      .map(([n]) => n);
    expect(crLines).toEqual([]);
  });

  test('has no byte-identical duplicate rows', () => {
    const seen = new Map();
    const dups = [];
    raw.split('\n').forEach((line, i) => {
      if (line === '') return; // ignore blank / trailing lines
      if (seen.has(line)) dups.push({ firstLine: seen.get(line) + 1, dupLine: i + 1, head: line.slice(0, 24) });
      else seen.set(line, i);
    });
    expect(dups).toEqual([]);
  });
});
