'use strict';

const fs = require('fs');
const path = require('path');

// Shiki v1 registers custom grammars under grammar.name (e.g. "lcc"), NOT
// grammar.scopeName (e.g. "source.lcc"). Any codeToHtml({ lang: ... }) call
// must use the name value — scopeName silently fails on cold (uncached) loads.
//
// The deployed Sandbox at /sandbox/ is GENERATED by scripts/build-site.js
// (docs/site/sandbox/index.html); the former standalone source pages
// docs/showcase/index.html + docs/playground/index.html were removed in #1045
// so fixes can no longer land on a non-deployed copy. Assert the invariant on
// the generator, which is the surface that actually ships.
test('build-site.js uses lang: lcc not lang: source.lcc in codeToHtml calls', () => {
  const src = fs.readFileSync(
    path.join(__dirname, '../../scripts/build-site.js'), 'utf8'
  );
  expect(src).not.toMatch(/lang:\s*['"]source\.lcc['"]/);
  expect(src).toMatch(/lang:\s*['"]lcc['"]/);
});

// #1334 — the docs sections (Guides/Research/Learnings/Glossary/Parity) used to
// force light mode regardless of the site theme toggle. Two causes in
// build-site.js, both asserted here against the generator (the surface that ships):
//
//   1. Docs pages were generated with a hardcoded `bodyClass: 'light'`. The CSS
//      defines the theme vars on BOTH `html.X` and `body.X`, so a baked
//      `body.light` redefined `--bg`/`--fg`/... on the body element and shadowed
//      the correct `html.dark` vars that the pre-paint head script sets — the
//      page rendered light no matter what. The fix bakes no theme class on docs
//      pages so the pre-paint <html> class drives them (and avoids a FOUC).
//
//   2. The shared on-load JS only synced the theme via `apply()` when a
//      `#theme-select` dropdown existed. Docs pages have a `#theme-toggle` button
//      but no dropdown, so `<body>`'s class was never reconciled on load. The fix
//      mirrors `document.documentElement.className` onto `document.body` for the
//      no-dropdown case.
describe('docs pages honor the active theme, not forced light (#1334)', () => {
  const src = fs.readFileSync(
    path.join(__dirname, '../../scripts/build-site.js'), 'utf8'
  );

  test('no page is generated with a hardcoded light body class', () => {
    expect(src).not.toMatch(/bodyClass:\s*['"]light['"]/);
  });
});

// #1379 — the site previously had TWO theme controls: a light/dark toggle button
// (#theme-toggle) and the theme dropdown (#theme-select). They were unified into
// ONE — the dropdown, now present on every page including docs (which previously
// had only the toggle). The standalone toggle button — its markup, its CSS class,
// and all its JS handlers — was removed. (Decided + implemented as pair-work; see
// the ruling on #1379.) This supersedes the #1334 no-dropdown body-class mirror:
// docs pages now reconcile their theme through the dropdown's apply() on load, so
// the #1334 outcome (docs follow the active theme, never forced light) still holds
// and is browser-verified against the built page.
describe('unified theme control — single dropdown, no standalone toggle (#1379)', () => {
  const src = fs.readFileSync(
    path.join(__dirname, '../../scripts/build-site.js'), 'utf8'
  );

  test('all traces of the #theme-toggle button (markup, CSS, JS) are removed', () => {
    expect(src).not.toMatch(/theme-toggle/);
  });

  test('the #theme-select dropdown remains the theme control', () => {
    expect(src).toMatch(/id="theme-select"/);
  });
});

// #1333 — the sandbox input/output SURFACES (output pane #exec-output, stdin
// textarea #stdin-input, the stdin prompt) drew their background/foreground from
// the page light/dark vars (var(--border)/var(--fg)), NOT the active code theme's
// palette. So on e.g. Monokai the editor showed Monokai's background but the
// surfaces showed a generic github-dark background — the editor and the terminal
// disagreed. The fix drives the surfaces from a --surface-bg/--surface-fg pair
// that JS sets from the SAME precomputed LCC_THEME_STYLES[theme] palette the
// editor's chromeTheme() consumes, so all surfaces track the code theme.
describe('sandbox surfaces follow the code-theme palette, not page light/dark (#1333)', () => {
  const src = fs.readFileSync(
    path.join(__dirname, '../../scripts/build-site.js'), 'utf8'
  );

  test('surfaces reference the per-theme --surface-bg/--surface-fg vars', () => {
    expect(src).toMatch(/--surface-bg/);
    expect(src).toMatch(/--surface-fg/);
  });

  test('applySurfaceTheme drives --surface-* from the LCC_THEME_STYLES palette', () => {
    expect(src).toMatch(/applySurfaceTheme/);
    expect(src).toMatch(/setProperty\(\s*['"]--surface-bg['"]/);
  });
});

// #1388 — docs-prose fenced ```lcc code blocks were baked at build time with a
// single light Shiki theme (DOCS_CODE_THEME = 'github-light'), so once docs pages
// became theme-aware (#1334) and got the theme dropdown (#1379), those blocks
// rendered as white "islands" on a dark page. The fix bakes one Shiki variant per
// theme as hidden .theme-panel elements (like the landing page's renderSnippet),
// which the shared apply() already toggles by the active theme — so a docs code
// block now matches the selected theme's palette. Browser-verified against the
// built page.
describe('docs-prose code blocks follow the active theme, no light island (#1388)', () => {
  const src = fs.readFileSync(
    path.join(__dirname, '../../scripts/build-site.js'), 'utf8'
  );

  test('the single-theme DOCS_CODE_THEME bake is gone', () => {
    expect(src).not.toMatch(/DOCS_CODE_THEME/);
  });

  test('the lcc fenced-block renderer emits per-theme .theme-panel variants', () => {
    expect(src).toMatch(/token\.lang === 'lcc'[\s\S]*?theme-panel/);
  });
});
